let races = [{
    allocation: 13439,
    betTypesAuthorized: ["simple", "couplé", "2/4"],
    category: "Attelé",
    direction: "Corde à droite",
    distance: 2861,
    equidiaPronostic: [7, 4, 2, 5, 6],
    field: "Piste en gazon",
    horses: ["Jarl", "Courageously", "Van Dusen", "El Magnifico", "El Campana", "Papi Chulo", "Gran Stylo", "Hussarde"],
    hour: "8:15",
    id: 0,
    location: "VINCENNES",
    locationCode: "R4",
    pace: "Trot",
    raceCode: "C1",
    raceTitle: "PRIX ST LEGER S",
    weekDayID: 0
  }, {
    allocation: 5136,
    betTypesAuthorized: ["simple"],
    category: "Plat",
    direction: "Corde à droite",
    distance: 2066,
    equidiaPronostic: [5, 2, 9, 1, 8],
    field: "Piste en gazon",
    horses: ["Munqad", "Houston Sissi", "Andre Tor", "El Campana", "Haka", "El Campana", "Haka", "Winning Point", "Munqad", "Hussarde", "Happy Lyl", "Ultimate Gift"],
    hour: "8:45",
    id: 1,
    location: "GULFSTREAM",
    locationCode: "R5",
    pace: "Gallop",
    raceCode: "C2",
    raceTitle: "PRIX VALLEE VESUBIE",
    weekDayID: 0
  }, {
    allocation: 41738,
    betTypesAuthorized: ["simple"],
    category: "Crosscountry",
    direction: "Corde à gauche",
    distance: 2135,
    equidiaPronostic: [2, 1, 3, 0, 8],
    field: "Piste en cendre",
    horses: ["Happy Lyl", "Hussarde", "Jarl", "Romeo Santos", "Andre Tor", "El Campana", "Ultimate Gift", "Romeo Santos", "El Magnifico"],
    hour: "9:45",
    id: 2,
    location: "CAGNES/MER",
    locationCode: "R2",
    pace: "Gallop",
    raceCode: "C3",
    raceTitle: "PRIX WOLF",
    weekDayID: 0
  }, {
    allocation: 92662,
    betTypesAuthorized: ["simple", "couplé", "2/4"],
    category: " Monté",
    direction: "Corde à droite",
    distance: 2451,
    equidiaPronostic: [0, 6, 4, 12, 8],
    field: "Piste en sable fibré",
    horses: ["Romeo Santos", "El Magnifico", "Jarl", "Papi Chulo", "Heaven De Simm", "Hussarde", "Heaven De Simm", "Van Dusen", "Munqad", "Jarl", "Ultimate Gift", "Van Dusen", "Hani Bird", "Romeo Santos", "Munqad", "Winning Point"],
    hour: "10:45",
    id: 3,
    location: "CHILE",
    locationCode: "R2",
    pace: "Trot",
    raceCode: "C4",
    raceTitle: "PRIX DU MERCANTOUR",
    weekDayID: 0
  }, {
    allocation: 33529,
    betTypesAuthorized: ["simple"],
    category: "Attelé",
    direction: "Corde à gauche",
    distance: 2722,
    equidiaPronostic: [2, 8, 3, 4, 0],
    field: "Piste en pouzzolane",
    horses: ["Houston Sissi", "Tsitsipas", "Houston Sissi", "Jarl", "Hallezsco", "Happy Lyl", "Romeo Santos", "Ultimate Gift", "El Magnifico"],
    hour: "11:00",
    id: 4,
    location: "AGEN LA GA.",
    locationCode: "R4",
    pace: "Trot",
    raceCode: "C5",
    raceTitle: "PRIX MAIDEN SPECIAL",
    weekDayID: 0
  }, {
    allocation: 10981,
    betTypesAuthorized: ["simple"],
    category: "Crosscountry",
    direction: "Corde à gauche",
    distance: 2035,
    equidiaPronostic: [5, 4, 12, 3, 10],
    field: "Piste en gazon",
    horses: ["El Campana", "Andre Tor", "Courageously", "Happy Lyl", "Hani Bird", "Hussarde", "Hani Bird", "Andre Tor", "Andre Tor", "Courageously", "Tsitsipas", "Ultimate Gift", "Houston Sissi"],
    hour: "11:30",
    id: 5,
    location: "AGEN LA GA.",
    locationCode: "R3",
    pace: "Gallop",
    raceCode: "C6",
    raceTitle: "PRIX VALLEE VESUBIE",
    weekDayID: 0
  }, {
    allocation: 17774,
    betTypesAuthorized: ["simple"],
    category: "Attelé",
    direction: "Corde à gauche",
    distance: 2204,
    equidiaPronostic: [6, 2, 4, 0, 3],
    field: "Piste en cendre",
    horses: ["El Campana", "Haka", "Houston Sissi", "Heaven De Simm", "Ultimate Gift", "El Magnifico", "Houston Sissi"],
    hour: "12:00",
    id: 6,
    location: "VINCENNES",
    locationCode: "R6",
    pace: "Trot",
    raceCode: "C7",
    raceTitle: "PRIX MAIDEN SPECIAL",
    weekDayID: 0
  }, {
    allocation: 22323,
    betTypesAuthorized: ["simple", "couplé", "2/4"],
    category: " Monté",
    direction: "Corde à droite",
    distance: 2216,
    equidiaPronostic: [4, 3, 2, 0, 1],
    field: "Piste en cendre",
    horses: ["Munqad", "Heaven De Simm", "Winning Point", "Hallezsco", "Jarl"],
    hour: "12:15",
    id: 7,
    location: "VINCENNES",
    locationCode: "R6",
    pace: "Trot",
    raceCode: "C8",
    raceTitle: "PRIX MELONERO H",
    weekDayID: 0
  }, {
    allocation: 46793,
    betTypesAuthorized: ["simple"],
    category: "Steeplechase",
    direction: "Corde à gauche",
    distance: 2925,
    equidiaPronostic: [10, 4, 11, 6, 2],
    field: "Piste en gazon",
    horses: ["Hallezsco", "Ultimate Gift", "El Magnifico", "El Magnifico", "Heaven De Simm", "Papi Chulo", "Haka", "Haka", "Romeo Santos", "Happy Lyl", "Tsitsipas", "Papi Chulo"],
    hour: "9:00",
    id: 1,
    location: "GULFSTREAM",
    locationCode: "R2",
    pace: "Gallop",
    raceCode: "C1",
    raceTitle: "PRIX MR. PROSPECTOR",
    weekDayID: 1
  }, {
    allocation: 41519,
    betTypesAuthorized: ["simple", "couplé"],
    category: "Attelé",
    direction: "Corde à droite",
    distance: 2770,
    equidiaPronostic: [13, 7, 4, 8, 12],
    field: "Piste en pouzzolane",
    horses: ["Tsitsipas", "Romeo Santos", "Heaven De Simm", "El Magnifico", "Happy Lyl", "Gran Stylo", "Van Dusen", "Ultimate Gift", "Andre Tor", "Ultimate Gift", "Hallezsco", "Papi Chulo", "Papi Chulo", "Hallezsco", "Courageously"],
    hour: "10:00",
    id: 2,
    location: "VINCENNES",
    locationCode: "R3",
    pace: "Trot",
    raceCode: "C2",
    raceTitle: "PRIX MAIDEN SPECIAL",
    weekDayID: 1
  }, {
    allocation: 34397,
    betTypesAuthorized: ["simple", "couplé", "2/4"],
    category: " Monté",
    direction: "Corde à gauche",
    distance: 2019,
    equidiaPronostic: [4, 8, 5, 0, 10],
    field: "Piste en gazon",
    horses: ["El Magnifico", "Winning Point", "Hussarde", "Papi Chulo", "Romeo Santos", "Haka", "Heaven De Simm", "Haka", "Van Dusen", "Winning Point", "Winning Point", "El Magnifico"],
    hour: "10:30",
    id: 3,
    location: "AGEN LA GA.",
    locationCode: "R5",
    pace: "Trot",
    raceCode: "C3",
    raceTitle: "PRIX ST LEGER S",
    weekDayID: 1
  }, {
    allocation: 4947,
    betTypesAuthorized: ["simple"],
    category: "Attelé",
    direction: "Corde à droite",
    distance: 2177,
    equidiaPronostic: [12, 3, 5, 0, 9],
    field: "Piste en herbe",
    horses: ["Papi Chulo", "Ultimate Gift", "Hussarde", "Ultimate Gift", "Van Dusen", "Hussarde", "Hallezsco", "Munqad", "Romeo Santos", "Jarl", "Haka", "Hussarde", "Jarl", "Haka", "Haka"],
    hour: "11:30",
    id: 4,
    location: "VINCENNES",
    locationCode: "R5",
    pace: "Trot",
    raceCode: "C4",
    raceTitle: "PRIX VALLEE VESUBIE",
    weekDayID: 1
  }, {
    allocation: 10335,
    betTypesAuthorized: ["simple", "couplé", "2/4"],
    category: "Attelé",
    direction: "Corde à gauche",
    distance: 2569,
    equidiaPronostic: [0, 6, 4, 2, 8],
    field: "Piste en sable fibré",
    horses: ["Ultimate Gift", "El Campana", "Hani Bird", "Van Dusen", "Houston Sissi", "Happy Lyl", "Gran Stylo", "Haka", "Gran Stylo", "El Campana"],
    hour: "12:30",
    id: 5,
    location: "CHILE",
    locationCode: "R3",
    pace: "Trot",
    raceCode: "C5",
    raceTitle: "PRIX INICIACION S",
    weekDayID: 1
  }, {
    allocation: 26419,
    betTypesAuthorized: ["simple", "couplé"],
    category: "Crosscountry",
    direction: "Corde à droite",
    distance: 2392,
    equidiaPronostic: [0, 12, 1, 5, 14],
    field: "Piste en cendre",
    horses: ["Hani Bird", "Winning Point", "Papi Chulo", "El Campana", "Munqad", "Romeo Santos", "Papi Chulo", "Ultimate Gift", "El Magnifico", "Winning Point", "Courageously", "Courageously", "Heaven De Simm", "Houston Sissi", "Ultimate Gift"],
    hour: "12:45",
    id: 6,
    location: "AGEN LA GA.",
    locationCode: "R4",
    pace: "Gallop",
    raceCode: "C6",
    raceTitle: "PRIX TROMPOLINO",
    weekDayID: 1
  }, {
    allocation: 25404,
    betTypesAuthorized: ["simple", "couplé"],
    category: " Monté",
    direction: "Corde à droite",
    distance: 2751,
    equidiaPronostic: [12, 6, 4, 0, 11],
    field: "Piste en sable fibré",
    horses: ["El Campana", "El Campana", "Jarl", "Papi Chulo", "Andre Tor", "Heaven De Simm", "Haka", "Papi Chulo", "Munqad", "Gran Stylo", "Hani Bird", "Andre Tor", "Van Dusen", "El Magnifico"],
    hour: "13:00",
    id: 7,
    location: "CHILE",
    locationCode: "R5",
    pace: "Trot",
    raceCode: "C7",
    raceTitle: "PRIX DU MERCANTOUR",
    weekDayID: 1
  }, {
    allocation: 9908,
    betTypesAuthorized: ["simple", "couplé", "2/4"],
    category: " Monté",
    direction: "Corde à gauche",
    distance: 2750,
    equidiaPronostic: [13, 5, 9, 7, 11],
    field: "Piste en gazon",
    horses: ["Papi Chulo", "El Magnifico", "Tsitsipas", "Courageously", "Romeo Santos", "Houston Sissi", "Andre Tor", "Winning Point", "Hussarde", "Romeo Santos", "Gran Stylo", "Haka", "Jarl", "Gran Stylo", "Tsitsipas", "Winning Point", "Van Dusen", "El Magnifico", "El Magnifico"],
    hour: "13:15",
    id: 8,
    location: "AGEN LA GA.",
    locationCode: "R5",
    pace: "Trot",
    raceCode: "C8",
    raceTitle: "PRIX MELONERO H",
    weekDayID: 1
  }, {
    allocation: 70450,
    betTypesAuthorized: ["simple", "couplé"],
    category: "Attelé",
    direction: "Corde à droite",
    distance: 2287,
    equidiaPronostic: [4, 7, 2, 9, 6],
    field: "Piste en pouzzolane",
    horses: ["Hani Bird", "Houston Sissi", "Van Dusen", "Happy Lyl", "Winning Point", "Hussarde", "Andre Tor", "Papi Chulo", "Hussarde", "Courageously", "Andre Tor", "Andre Tor", "Romeo Santos", "Houston Sissi"],
    hour: "9:00",
    id: 2,
    location: "CAGNES/MER",
    locationCode: "R1",
    pace: "Trot",
    raceCode: "C1",
    raceTitle: "PRIX VALLEE VESUBIE",
    weekDayID: 2
  }, {
    allocation: 6025,
    betTypesAuthorized: ["simple", "couplé"],
    category: "Plat",
    direction: "Corde à gauche",
    distance: 2067,
    equidiaPronostic: [2, 12, 1, 13, 16],
    field: "Piste en herbe",
    horses: ["Munqad", "Munqad", "Happy Lyl", "El Campana", "Gran Stylo", "Van Dusen", "Tsitsipas", "Van Dusen", "Courageously", "Gran Stylo", "Ultimate Gift", "Jarl", "El Campana", "Ultimate Gift", "Van Dusen", "Van Dusen", "Ultimate Gift", "Houston Sissi"],
    hour: "9:30",
    id: 3,
    location: "CAGNES/MER",
    locationCode: "R4",
    pace: "Gallop",
    raceCode: "C2",
    raceTitle: "PRIX MELONERO H",
    weekDayID: 2
  }, {
    allocation: 98158,
    betTypesAuthorized: ["simple"],
    category: "Crosscountry",
    direction: "Corde à gauche",
    distance: 2781,
    equidiaPronostic: [10, 11, 7, 5, 12],
    field: "Piste en herbe",
    horses: ["Houston Sissi", "Heaven De Simm", "Papi Chulo", "Hussarde", "Ultimate Gift", "Hallezsco", "Andre Tor", "El Campana", "Hani Bird", "Gran Stylo", "Tsitsipas", "Haka", "Gran Stylo"],
    hour: "10:15",
    id: 4,
    location: "DEAUVILLE",
    locationCode: "R3",
    pace: "Gallop",
    raceCode: "C3",
    raceTitle: "PRIX MR. PROSPECTOR",
    weekDayID: 2
  }, {
    allocation: 68126,
    betTypesAuthorized: ["simple"],
    category: "Attelé",
    direction: "Corde à gauche",
    distance: 2637,
    equidiaPronostic: [7, 11, 1, 9, 8],
    field: "Pist en mâchefer",
    horses: ["Winning Point", "Jarl", "Munqad", "Houston Sissi", "El Campana", "Van Dusen", "Happy Lyl", "Happy Lyl", "Haka", "Haka", "Munqad", "Hani Bird"],
    hour: "10:45",
    id: 5,
    location: "GULFSTREAM",
    locationCode: "R6",
    pace: "Trot",
    raceCode: "C4",
    raceTitle: "PRIX VALLEE VESUBIE",
    weekDayID: 2
  }, {
    allocation: 74353,
    betTypesAuthorized: ["simple"],
    category: "Steeplechase",
    direction: "Corde à gauche",
    distance: 2152,
    equidiaPronostic: [2, 10, 4, 0, 5],
    field: "Piste en pouzzolane",
    horses: ["Haka", "Jarl", "Ultimate Gift", "Jarl", "Munqad", "Jarl", "Gran Stylo", "Romeo Santos", "Tsitsipas", "Papi Chulo", "Hani Bird"],
    hour: "9:00",
    id: 3,
    location: "VINCENNES",
    locationCode: "R3",
    pace: "Gallop",
    raceCode: "C1",
    raceTitle: "PRIX VAL.MERVEILLES",
    weekDayID: 3
  }, {
    allocation: 38029,
    betTypesAuthorized: ["simple", "couplé", "2/4"],
    category: "Attelé",
    direction: "Corde à gauche",
    distance: 2963,
    equidiaPronostic: [10, 5, 0, 4, 1],
    field: "Piste en herbe",
    horses: ["Ultimate Gift", "Hussarde", "Heaven De Simm", "Happy Lyl", "Jarl", "Andre Tor", "Tsitsipas", "Winning Point", "Andre Tor", "Van Dusen", "El Magnifico", "Munqad", "Gran Stylo"],
    hour: "9:45",
    id: 4,
    location: "CAGNES/MER",
    locationCode: "R5",
    pace: "Trot",
    raceCode: "C2",
    raceTitle: "PRIX INICIACION S",
    weekDayID: 3
  }, {
    allocation: 36048,
    betTypesAuthorized: ["simple"],
    category: " Monté",
    direction: "Corde à gauche",
    distance: 2890,
    equidiaPronostic: [5, 7, 4, 6, 8],
    field: "Piste en sable fibré",
    horses: ["El Magnifico", "Hallezsco", "Ultimate Gift", "Van Dusen", "Gran Stylo", "Ultimate Gift", "Hani Bird", "Papi Chulo", "Munqad", "Hussarde", "Hallezsco", "Heaven De Simm", "Papi Chulo", "Gran Stylo", "Van Dusen", "Munqad"],
    hour: "10:45",
    id: 5,
    location: "CAGNES/MER",
    locationCode: "R1",
    pace: "Trot",
    raceCode: "C3",
    raceTitle: "PRIX WOLF",
    weekDayID: 3
  }, {
    allocation: 3894,
    betTypesAuthorized: ["simple"],
    category: "Attelé",
    direction: "Corde à droite",
    distance: 2254,
    equidiaPronostic: [3, 5, 4, 9, 2],
    field: "Piste en cendre",
    horses: ["Papi Chulo", "Gran Stylo", "El Magnifico", "Haka", "Romeo Santos", "Courageously", "Houston Sissi", "El Campana", "Heaven De Simm", "Munqad", "Gran Stylo", "Hallezsco"],
    hour: "11:15",
    id: 6,
    location: "CAGNES/MER",
    locationCode: "R3",
    pace: "Trot",
    raceCode: "C4",
    raceTitle: "PRIX ALLOWANCE 1700",
    weekDayID: 3
  }, {
    allocation: 80852,
    betTypesAuthorized: ["simple", "couplé"],
    category: "Crosscountry",
    direction: "Corde à gauche",
    distance: 2804,
    equidiaPronostic: [1, 7, 2, 8, 6],
    field: "Piste en cendre",
    horses: ["Hallezsco", "Gran Stylo", "Gran Stylo", "Jarl", "Ultimate Gift", "Tsitsipas", "Ultimate Gift", "Courageously", "El Magnifico"],
    hour: "11:45",
    id: 7,
    location: "GULFSTREAM",
    locationCode: "R2",
    pace: "Gallop",
    raceCode: "C5",
    raceTitle: "PRIX VAL.MERVEILLES",
    weekDayID: 3
  }, {
    allocation: 47508,
    betTypesAuthorized: ["simple", "couplé"],
    category: " Monté",
    direction: "Corde à droite",
    distance: 2798,
    equidiaPronostic: [8, 10, 3, 9, 0],
    field: "Pist en mâchefer",
    horses: ["Van Dusen", "Munqad", "Happy Lyl", "Van Dusen", "Munqad", "Winning Point", "Munqad", "El Campana", "Ultimate Gift", "Courageously", "Happy Lyl", "Happy Lyl", "Hallezsco"],
    hour: "12:30",
    id: 8,
    location: "GULFSTREAM",
    locationCode: "R2",
    pace: "Trot",
    raceCode: "C6",
    raceTitle: "PRIX WOLF",
    weekDayID: 3
  }, {
    allocation: 41773,
    betTypesAuthorized: ["simple", "couplé"],
    category: " Monté",
    direction: "Corde à gauche",
    distance: 2234,
    equidiaPronostic: [7, 8, 1, 12, 13],
    field: "Piste en sable fibré",
    horses: ["Houston Sissi", "El Magnifico", "Munqad", "Happy Lyl", "El Magnifico", "Jarl", "Gran Stylo", "Tsitsipas", "Heaven De Simm", "Heaven De Simm", "Winning Point", "Romeo Santos", "Heaven De Simm", "Munqad"],
    hour: "12:45",
    id: 9,
    location: "VINCENNES",
    locationCode: "R4",
    pace: "Trot",
    raceCode: "C7",
    raceTitle: "PRIX MELONERO H",
    weekDayID: 3
  }, {
    allocation: 98315,
    betTypesAuthorized: ["simple"],
    category: " Monté",
    direction: "Corde à gauche",
    distance: 2203,
    equidiaPronostic: [4, 3, 6, 0, 1],
    field: "Piste en herbe",
    horses: ["Ultimate Gift", "El Magnifico", "Jarl", "Hussarde", "Houston Sissi", "Van Dusen", "El Campana", "Ultimate Gift", "Papi Chulo"],
    hour: "8:45",
    id: 4,
    location: "GULFSTREAM",
    locationCode: "R1",
    pace: "Trot",
    raceCode: "C1",
    raceTitle: "PRIX MR. PROSPECTOR",
    weekDayID: 4
  }, {
    allocation: 17864,
    betTypesAuthorized: ["simple"],
    category: " Monté",
    direction: "Corde à gauche",
    distance: 2855,
    equidiaPronostic: [5, 1, 3, 0, 2],
    field: "Piste en pouzzolane",
    horses: ["Jarl", "Heaven De Simm", "Munqad", "Gran Stylo", "El Campana", "Happy Lyl"],
    hour: "9:45",
    id: 5,
    location: "GULFSTREAM",
    locationCode: "R4",
    pace: "Trot",
    raceCode: "C2",
    raceTitle: "PRIX VAL.MERVEILLES",
    weekDayID: 4
  }, {
    allocation: 18541,
    betTypesAuthorized: ["simple", "couplé"],
    category: "Saut de haies",
    direction: "Corde à gauche",
    distance: 2403,
    equidiaPronostic: [7, 5, 2, 8, 1],
    field: "Piste en herbe",
    horses: ["Winning Point", "Papi Chulo", "Happy Lyl", "Haka", "Munqad", "El Magnifico", "Hussarde", "Courageously", "Haka"],
    hour: "10:15",
    id: 6,
    location: "DEAUVILLE",
    locationCode: "R3",
    pace: "Gallop",
    raceCode: "C3",
    raceTitle: "PRIX MELONERO H",
    weekDayID: 4
  }, {
    allocation: 22864,
    betTypesAuthorized: ["simple", "couplé", "2/4"],
    category: "Attelé",
    direction: "Corde à gauche",
    distance: 2067,
    equidiaPronostic: [4, 6, 1, 3, 7],
    field: "Piste en herbe",
    horses: ["Jarl", "Andre Tor", "Van Dusen", "Ultimate Gift", "Munqad", "Houston Sissi", "Hallezsco", "Tsitsipas", "Romeo Santos", "El Magnifico"],
    hour: "10:30",
    id: 7,
    location: "DEAUVILLE",
    locationCode: "R4",
    pace: "Trot",
    raceCode: "C4",
    raceTitle: "PRIX MR. PROSPECTOR",
    weekDayID: 4
  }, {
    allocation: 50800,
    betTypesAuthorized: ["simple", "couplé"],
    category: "Plat",
    direction: "Corde à droite",
    distance: 2956,
    equidiaPronostic: [1, 0, 8, 9, 3],
    field: "Piste en pouzzolane",
    horses: ["Houston Sissi", "El Campana", "El Campana", "Houston Sissi", "Winning Point", "Gran Stylo", "Hallezsco", "Happy Lyl", "Happy Lyl", "Winning Point"],
    hour: "11:00",
    id: 8,
    location: "AGEN LA GA.",
    locationCode: "R1",
    pace: "Gallop",
    raceCode: "C5",
    raceTitle: "PRIX MR. PROSPECTOR",
    weekDayID: 4
  }, {
    allocation: 21819,
    betTypesAuthorized: ["simple"],
    category: "Crosscountry",
    direction: "Corde à droite",
    distance: 2699,
    equidiaPronostic: [2, 4, 6, 1, 3],
    field: "Piste en herbe",
    horses: ["Jarl", "Munqad", "Courageously", "Winning Point", "Tsitsipas", "Heaven De Simm", "Winning Point", "Jarl", "Tsitsipas", "El Magnifico"],
    hour: "12:00",
    id: 9,
    location: "VINCENNES",
    locationCode: "R3",
    pace: "Gallop",
    raceCode: "C6",
    raceTitle: "PRIX ALLOWANCE 1700",
    weekDayID: 4
  }, {
    allocation: 82747,
    betTypesAuthorized: ["simple", "couplé", "2/4"],
    category: " Monté",
    direction: "Corde à droite",
    distance: 2504,
    equidiaPronostic: [3, 1, 8, 9, 6],
    field: "Piste en herbe",
    horses: ["Courageously", "Andre Tor", "El Campana", "Haka", "Houston Sissi", "Andre Tor", "El Magnifico", "Houston Sissi", "Haka", "Hani Bird"],
    hour: "8:30",
    id: 5,
    location: "GULFSTREAM",
    locationCode: "R2",
    pace: "Trot",
    raceCode: "C1",
    raceTitle: "PRIX DU MERCANTOUR",
    weekDayID: 5
  }, {
    allocation: 42809,
    betTypesAuthorized: ["simple", "couplé", "2/4"],
    category: "Attelé",
    direction: "Corde à gauche",
    distance: 2699,
    equidiaPronostic: [8, 7, 0, 5, 1],
    field: "Piste en sable fibré",
    horses: ["Jarl", "Van Dusen", "Gran Stylo", "Happy Lyl", "Winning Point", "Tsitsipas", "Ultimate Gift", "Hussarde", "Andre Tor", "Andre Tor"],
    hour: "9:00",
    id: 6,
    location: "AGEN LA GA.",
    locationCode: "R4",
    pace: "Trot",
    raceCode: "C2",
    raceTitle: "PRIX MELONERO H",
    weekDayID: 5
  }, {
    allocation: 82559,
    betTypesAuthorized: ["simple", "couplé", "2/4"],
    category: "Attelé",
    direction: "Corde à droite",
    distance: 2135,
    equidiaPronostic: [5, 1, 3, 0, 4],
    field: "Piste en pouzzolane",
    horses: ["Gran Stylo", "El Campana", "Haka", "Jarl", "Happy Lyl", "Ultimate Gift"],
    hour: "10:00",
    id: 7,
    location: "AGEN LA GA.",
    locationCode: "R2",
    pace: "Trot",
    raceCode: "C3",
    raceTitle: "PRIX WOLF",
    weekDayID: 5
  }, {
    allocation: 2561,
    betTypesAuthorized: ["simple"],
    category: " Monté",
    direction: "Corde à gauche",
    distance: 2077,
    equidiaPronostic: [13, 5, 7, 2, 15],
    field: "Pist en mâchefer",
    horses: ["Gran Stylo", "Romeo Santos", "Heaven De Simm", "Courageously", "Winning Point", "Van Dusen", "Houston Sissi", "Gran Stylo", "Hussarde", "El Magnifico", "Happy Lyl", "Houston Sissi", "Heaven De Simm", "Heaven De Simm", "Munqad", "Andre Tor", "Hallezsco"],
    hour: "10:30",
    id: 8,
    location: "VINCENNES",
    locationCode: "R5",
    pace: "Trot",
    raceCode: "C4",
    raceTitle: "PRIX VALLEE VESUBIE",
    weekDayID: 5
  }, {
    allocation: 40572,
    betTypesAuthorized: ["simple", "couplé"],
    category: "Attelé",
    direction: "Corde à gauche",
    distance: 2553,
    equidiaPronostic: [13, 7, 9, 14, 8],
    field: "Pist en mâchefer",
    horses: ["Munqad", "Munqad", "El Magnifico", "Jarl", "Courageously", "Ultimate Gift", "Jarl", "Hussarde", "Tsitsipas", "Romeo Santos", "Papi Chulo", "Van Dusen", "Courageously", "Van Dusen", "Heaven De Simm", "Munqad", "Van Dusen"],
    hour: "8:15",
    id: 6,
    location: "VINCENNES",
    locationCode: "R5",
    pace: "Trot",
    raceCode: "C1",
    raceTitle: "PRIX MR. PROSPECTOR",
    weekDayID: 6
  }, {
    allocation: 32937,
    betTypesAuthorized: ["simple", "couplé", "2/4"],
    category: "Plat",
    direction: "Corde à droite",
    distance: 2121,
    equidiaPronostic: [0, 5, 2, 3, 4],
    field: "Piste en gazon",
    horses: ["Hani Bird", "Winning Point", "Munqad", "Hani Bird", "Winning Point", "Romeo Santos", "El Magnifico"],
    hour: "9:15",
    id: 7,
    location: "DEAUVILLE",
    locationCode: "R3",
    pace: "Gallop",
    raceCode: "C2",
    raceTitle: "PRIX DU MERCANTOUR",
    weekDayID: 6
  }, {
    allocation: 66912,
    betTypesAuthorized: ["simple", "couplé", "2/4"],
    category: "Saut de haies",
    direction: "Corde à gauche",
    distance: 2204,
    equidiaPronostic: [11, 13, 16, 2, 3],
    field: "Piste en sable fibré",
    horses: ["Gran Stylo", "Happy Lyl", "Haka", "Van Dusen", "Papi Chulo", "Hussarde", "Jarl", "El Magnifico", "Winning Point", "Andre Tor", "Winning Point", "Jarl", "Haka", "Ultimate Gift", "El Campana", "Van Dusen", "Hussarde"],
    hour: "9:30",
    id: 8,
    location: "DEAUVILLE",
    locationCode: "R2",
    pace: "Gallop",
    raceCode: "C3",
    raceTitle: "PRIX LA SOLIDARITE",
    weekDayID: 6
  }, {
    allocation: 76761,
    betTypesAuthorized: ["simple", "couplé"],
    category: " Monté",
    direction: "Corde à gauche",
    distance: 2079,
    equidiaPronostic: [0, 8, 1, 4, 5],
    field: "Piste en sable fibré",
    horses: ["Jarl", "Andre Tor", "Van Dusen", "Tsitsipas", "Courageously", "Courageously", "Houston Sissi", "Tsitsipas", "Happy Lyl", "Munqad"],
    hour: "10:30",
    id: 9,
    location: "CHILE",
    locationCode: "R2",
    pace: "Trot",
    raceCode: "C4",
    raceTitle: "PRIX VAL.MERVEILLES",
    weekDayID: 6
  }]


export default races;