let races = [{
  allocation: 35320,
  category: "Attelé",
  direction: "Corde à gauche",
  distance: 2743,
  equidiaPronostic: [7, 8, 5, 0, 6],
  field: "Piste en cendre",
  horses: ["Hallezsco", "Heaven De Simm", "Hani Bird", "Romeo Santos", "Van Dusen", "Papi Chulo", "Andre Tor", "Ultimate Gift", "Gran Stylo"],
  hour: "08:15",
  id: 0,
  location: "CAGNES/MER",
  locationCode: "R6",
  pace: "Trot",
  raceCode: "C1",
  raceTitle: "PRIX DU MERCANTOUR",
  weekDayID: 0
}, {
  allocation: 21127,
  category: "Attelé",
  direction: "Corde à droite",
  distance: 2745,
  equidiaPronostic: [12, 2, 5, 11, 6],
  field: "Piste en sable",
  horses: ["Haka", "El Campana", "Romeo Santos", "Jarl", "Hussarde", "Winning Point", "Courageously", "Papi Chulo", "Van Dusen", "Hallezsco", "Houston Sissi", "Ultimate Gift", "Munqad", "Gran Stylo", "Happy Lyl", "Tsitsipas", "Hani Bird"],
  hour: "08:30",
  id: 1,
  location: "VINCENNES",
  locationCode: "R5",
  pace: "Trot",
  raceCode: "C2",
  raceTitle: "PRIX VALLEE VESUBIE",
  weekDayID: 0
}, {
  allocation: 64652,
  category: "Crosscountry",
  direction: "Corde à droite",
  distance: 2590,
  equidiaPronostic: [1, 2, 5, 3, 0],
  field: "Piste en cendre",
  horses: ["Andre Tor", "Gran Stylo", "El Magnifico", "Winning Point", "Happy Lyl", "Houston Sissi"],
  hour: "09:00",
  id: 2,
  location: "GULFSTREAM",
  locationCode: "R4",
  pace: "Gallop",
  raceCode: "C3",
  raceTitle: "PRIX INICIACION S",
  weekDayID: 0
}, {
  allocation: 92694,
  category: " Monté",
  direction: "Corde à droite",
  distance: 2576,
  equidiaPronostic: [13, 3, 7, 8, 10],
  field: "Piste en cendre",
  horses: ["Papi Chulo", "Andre Tor", "El Magnifico", "Tsitsipas", "Romeo Santos", "Gran Stylo", "Houston Sissi", "Ultimate Gift", "Jarl", "Haka", "Hallezsco", "Hani Bird", "Courageously", "Happy Lyl", "El Campana", "Winning Point", "Munqad"],
  hour: "09:45",
  id: 3,
  location: "GULFSTREAM",
  locationCode: "R5",
  pace: "Trot",
  raceCode: "C4",
  raceTitle: "PRIX LA SOLIDARITE",
  weekDayID: 0
}, {
  allocation: 23992,
  category: "Plat",
  direction: "Corde à droite",
  distance: 2863,
  equidiaPronostic: [2, 8, 3, 5, 13],
  field: "Piste en pouzzolane",
  horses: ["Romeo Santos", "Hani Bird", "Winning Point", "Jarl", "El Magnifico", "Papi Chulo", "Van Dusen", "Happy Lyl", "Andre Tor", "Haka", "El Campana", "Munqad", "Hallezsco", "Gran Stylo"],
  hour: "10:00",
  id: 4,
  location: "AGEN LA GA.",
  locationCode: "R1",
  pace: "Gallop",
  raceCode: "C5",
  raceTitle: "PRIX MR. PROSPECTOR",
  weekDayID: 0
}, {
  allocation: 8541,
  category: "Crosscountry",
  direction: "Corde à gauche",
  distance: 2081,
  equidiaPronostic: [2, 1, 0, 4, 3],
  field: "Piste en pouzzolane",
  horses: ["Houston Sissi", "Munqad", "Van Dusen", "Jarl", "Tsitsipas"],
  hour: "10:15",
  id: 5,
  location: "VINCENNES",
  locationCode: "R3",
  pace: "Gallop",
  raceCode: "C6",
  raceTitle: "PRIX MR. PROSPECTOR",
  weekDayID: 0
}, {
  allocation: 71829,
  category: "Plat",
  direction: "Corde à droite",
  distance: 2008,
  equidiaPronostic: [16, 5, 1, 6, 15],
  field: "Piste en herbe",
  horses: ["Ultimate Gift", "Romeo Santos", "Hallezsco", "Andre Tor", "Haka", "Van Dusen", "El Campana", "Happy Lyl", "Heaven De Simm", "Winning Point", "Munqad", "El Magnifico", "Jarl", "Hani Bird", "Papi Chulo", "Tsitsipas", "Houston Sissi", "Courageously"],
  hour: "11:15",
  id: 6,
  location: "VINCENNES",
  locationCode: "R2",
  pace: "Gallop",
  raceCode: "C7",
  raceTitle: "PRIX MELONERO H",
  weekDayID: 0
}, {
  allocation: 26448,
  category: "Plat",
  direction: "Corde à gauche",
  distance: 2031,
  equidiaPronostic: [8, 15, 3, 11, 2],
  field: "Pist en mâchefer",
  horses: ["Andre Tor", "Tsitsipas", "Hallezsco", "Papi Chulo", "Courageously", "El Campana", "Munqad", "Jarl", "El Magnifico", "Hani Bird", "Gran Stylo", "Haka", "Ultimate Gift", "Winning Point", "Happy Lyl", "Houston Sissi", "Hussarde"],
  hour: "11:30",
  id: 7,
  location: "CHILE",
  locationCode: "R6",
  pace: "Gallop",
  raceCode: "C8",
  raceTitle: "PRIX ST LEGER S",
  weekDayID: 0
}, {
  allocation: 46340,
  category: "Steeplechase",
  direction: "Corde à gauche",
  distance: 2901,
  equidiaPronostic: [1, 8, 9, 2, 4],
  field: "Piste en gazon",
  horses: ["Hallezsco", "Happy Lyl", "Jarl", "Tsitsipas", "Hussarde", "Winning Point", "Heaven De Simm", "Ultimate Gift", "Munqad", "Romeo Santos", "Gran Stylo", "El Magnifico", "Haka"],
  hour: "08:45",
  id: 8,
  location: "DEAUVILLE",
  locationCode: "R5",
  pace: "Gallop",
  raceCode: "C1",
  raceTitle: "PRIX LA SOLIDARITE",
  weekDayID: 1
}, {
  allocation: 69089,
  category: "Attelé",
  direction: "Corde à gauche",
  distance: 2165,
  equidiaPronostic: [1, 4, 6, 0, 5],
  field: "Piste en pouzzolane",
  horses: ["Ultimate Gift", "Munqad", "Gran Stylo", "Tsitsipas", "Romeo Santos", "El Campana", "Houston Sissi"],
  hour: "09:15",
  id: 9,
  location: "VINCENNES",
  locationCode: "R1",
  pace: "Trot",
  raceCode: "C2",
  raceTitle: "PRIX VALLEE VESUBIE",
  weekDayID: 1
}, {
  allocation: 56766,
  category: " Monté",
  direction: "Corde à gauche",
  distance: 2620,
  equidiaPronostic: [8, 11, 5, 13, 7],
  field: "Piste en pouzzolane",
  horses: ["Gran Stylo", "El Magnifico", "Papi Chulo", "Houston Sissi", "Happy Lyl", "Munqad", "Tsitsipas", "Hani Bird", "Romeo Santos", "El Campana", "Andre Tor", "Hallezsco", "Hussarde", "Van Dusen", "Ultimate Gift"],
  hour: "09:45",
  id: 10,
  location: "CAGNES/MER",
  locationCode: "R5",
  pace: "Trot",
  raceCode: "C3",
  raceTitle: "PRIX VALLEE VESUBIE",
  weekDayID: 1
}, {
  allocation: 86183,
  category: "Steeplechase",
  direction: "Corde à droite",
  distance: 2163,
  equidiaPronostic: [4, 1, 0, 3, 2],
  field: "Piste en sable",
  horses: ["Hussarde", "Tsitsipas", "El Campana", "Munqad", "El Magnifico"],
  hour: "10:15",
  id: 11,
  location: "AGEN LA GA.",
  locationCode: "R1",
  pace: "Gallop",
  raceCode: "C4",
  raceTitle: "PRIX LA SOLIDARITE",
  weekDayID: 1
}, {
  allocation: 64101,
  category: " Monté",
  direction: "Corde à droite",
  distance: 2161,
  equidiaPronostic: [8, 2, 3, 6, 9],
  field: "Piste en pouzzolane",
  horses: ["Hussarde", "Happy Lyl", "Hallezsco", "Gran Stylo", "El Magnifico", "Romeo Santos", "Courageously", "Andre Tor", "Hani Bird", "Winning Point"],
  hour: "10:45",
  id: 12,
  location: "CHILE",
  locationCode: "R6",
  pace: "Trot",
  raceCode: "C5",
  raceTitle: "PRIX WOLF",
  weekDayID: 1
}, {
  allocation: 98848,
  category: "Attelé",
  direction: "Corde à gauche",
  distance: 2438,
  equidiaPronostic: [6, 0, 10, 7, 1],
  field: "Pist en mâchefer",
  horses: ["Tsitsipas", "Happy Lyl", "Heaven De Simm", "Houston Sissi", "Van Dusen", "Hussarde", "Winning Point", "Gran Stylo", "Papi Chulo", "Hani Bird", "Haka", "El Magnifico", "Hallezsco", "El Campana"],
  hour: "08:15",
  id: 13,
  location: "AGEN LA GA.",
  locationCode: "R3",
  pace: "Trot",
  raceCode: "C1",
  raceTitle: "PRIX MAIDEN SPECIAL",
  weekDayID: 2
}, {
  allocation: 30580,
  category: "Attelé",
  direction: "Corde à droite",
  distance: 2385,
  equidiaPronostic: [2, 0, 4, 1, 3],
  field: "Piste en gazon",
  horses: ["Van Dusen", "Jarl", "Hussarde", "Tsitsipas", "Andre Tor", "Munqad", "El Campana", "Romeo Santos", "Houston Sissi"],
  hour: "09:15",
  id: 14,
  location: "CHILE",
  locationCode: "R5",
  pace: "Trot",
  raceCode: "C2",
  raceTitle: "PRIX VALLEE VESUBIE",
  weekDayID: 2
}, {
  allocation: 31091,
  category: "Saut de haies",
  direction: "Corde à gauche",
  distance: 2167,
  equidiaPronostic: [15, 7, 5, 12, 3],
  field: "Pist en mâchefer",
  horses: ["Hallezsco", "Heaven De Simm", "Winning Point", "Andre Tor", "Munqad", "Papi Chulo", "Happy Lyl", "Courageously", "Ultimate Gift", "Hani Bird", "Tsitsipas", "Gran Stylo", "Romeo Santos", "Jarl", "Hussarde", "El Magnifico", "El Campana", "Houston Sissi", "Haka"],
  hour: "09:45",
  id: 15,
  location: "CAGNES/MER",
  locationCode: "R2",
  pace: "Gallop",
  raceCode: "C3",
  raceTitle: "PRIX TROMPOLINO",
  weekDayID: 2
}, {
  allocation: 51421,
  category: "Crosscountry",
  direction: "Corde à droite",
  distance: 2412,
  equidiaPronostic: [5, 3, 1, 0, 7],
  field: "Pist en mâchefer",
  horses: ["Houston Sissi", "Gran Stylo", "Hussarde", "El Campana", "Tsitsipas", "Haka", "Munqad", "Winning Point", "Heaven De Simm"],
  hour: "10:00",
  id: 16,
  location: "DEAUVILLE",
  locationCode: "R2",
  pace: "Gallop",
  raceCode: "C4",
  raceTitle: "PRIX VAL.MERVEILLES",
  weekDayID: 2
}, {
  allocation: 39414,
  category: "Attelé",
  direction: "Corde à droite",
  distance: 2271,
  equidiaPronostic: [12, 7, 6, 15, 5],
  field: "Piste en sable",
  horses: ["Haka", "Andre Tor", "Hussarde", "El Campana", "Heaven De Simm", "Courageously", "Gran Stylo", "Munqad", "Hallezsco", "Tsitsipas", "Happy Lyl", "Romeo Santos", "Papi Chulo", "El Magnifico", "Houston Sissi", "Hani Bird", "Ultimate Gift", "Van Dusen", "Jarl"],
  hour: "10:30",
  id: 17,
  location: "VINCENNES",
  locationCode: "R4",
  pace: "Trot",
  raceCode: "C5",
  raceTitle: "PRIX MR. PROSPECTOR",
  weekDayID: 2
}, {
  allocation: 58381,
  category: " Monté",
  direction: "Corde à gauche",
  distance: 2334,
  equidiaPronostic: [5, 3, 4, 1, 0],
  field: "Piste en pouzzolane",
  horses: ["Haka", "El Campana", "Hani Bird", "Winning Point", "Tsitsipas", "El Magnifico"],
  hour: "11:30",
  id: 18,
  location: "DEAUVILLE",
  locationCode: "R2",
  pace: "Trot",
  raceCode: "C6",
  raceTitle: "PRIX VAL.MERVEILLES",
  weekDayID: 2
}, {
  allocation: 71391,
  category: "Plat",
  direction: "Corde à gauche",
  distance: 2180,
  equidiaPronostic: [8, 7, 5, 2, 9],
  field: "Piste en cendre",
  horses: ["Happy Lyl", "Munqad", "El Campana", "Van Dusen", "Winning Point", "Courageously", "Hani Bird", "Ultimate Gift", "Houston Sissi", "Papi Chulo", "Hussarde", "El Magnifico"],
  hour: "08:30",
  id: 19,
  location: "VINCENNES",
  locationCode: "R6",
  pace: "Gallop",
  raceCode: "C1",
  raceTitle: "PRIX INICIACION S",
  weekDayID: 3
}, {
  allocation: 7292,
  category: "Steeplechase",
  direction: "Corde à droite",
  distance: 2156,
  equidiaPronostic: [2, 8, 12, 1, 4],
  field: "Pist en mâchefer",
  horses: ["Hallezsco", "Hussarde", "Haka", "Romeo Santos", "Jarl", "Houston Sissi", "El Campana", "Winning Point", "Heaven De Simm", "Gran Stylo", "Ultimate Gift", "Andre Tor", "Tsitsipas"],
  hour: "08:45",
  id: 20,
  location: "CHILE",
  locationCode: "R3",
  pace: "Gallop",
  raceCode: "C2",
  raceTitle: "PRIX VALLEE VESUBIE",
  weekDayID: 3
}, {
  allocation: 83968,
  category: "Attelé",
  direction: "Corde à gauche",
  distance: 2782,
  equidiaPronostic: [5, 6, 4, 3, 0],
  field: "Piste en sable",
  horses: ["Heaven De Simm", "Gran Stylo", "Tsitsipas", "Andre Tor", "Houston Sissi", "Courageously", "Happy Lyl", "Van Dusen", "El Magnifico"],
  hour: "09:30",
  id: 21,
  location: "VINCENNES",
  locationCode: "R2",
  pace: "Trot",
  raceCode: "C3",
  raceTitle: "PRIX DU MERCANTOUR",
  weekDayID: 3
}, {
  allocation: 43288,
  category: "Attelé",
  direction: "Corde à gauche",
  distance: 2733,
  equidiaPronostic: [11, 6, 0, 8, 3],
  field: "Piste en gazon",
  horses: ["Hussarde", "Hani Bird", "Hallezsco", "Houston Sissi", "Winning Point", "Tsitsipas", "Jarl", "El Magnifico", "Ultimate Gift", "Heaven De Simm", "Papi Chulo", "Van Dusen"],
  hour: "08:45",
  id: 22,
  location: "AGEN LA GA.",
  locationCode: "R2",
  pace: "Trot",
  raceCode: "C1",
  raceTitle: "PRIX ST LEGER S",
  weekDayID: 4
}, {
  allocation: 31200,
  category: " Monté",
  direction: "Corde à gauche",
  distance: 2395,
  equidiaPronostic: [2, 12, 11, 0, 1],
  field: "Pist en mâchefer",
  horses: ["El Magnifico", "Haka", "Romeo Santos", "Tsitsipas", "Andre Tor", "Papi Chulo", "Van Dusen", "Hallezsco", "Courageously", "Hani Bird", "Heaven De Simm", "Hussarde", "Houston Sissi", "Gran Stylo"],
  hour: "09:30",
  id: 23,
  location: "GULFSTREAM",
  locationCode: "R3",
  pace: "Trot",
  raceCode: "C2",
  raceTitle: "PRIX ST LEGER S",
  weekDayID: 4
}, {
  allocation: 6880,
  category: " Monté",
  direction: "Corde à gauche",
  distance: 2306,
  equidiaPronostic: [1, 2, 3, 4, 5],
  field: "Piste en sable fibré",
  horses: ["Munqad", "Winning Point", "Andre Tor", "Heaven De Simm", "Romeo Santos", "Hussarde", "El Campana"],
  hour: "10:30",
  id: 24,
  location: "VINCENNES",
  locationCode: "R3",
  pace: "Trot",
  raceCode: "C3",
  raceTitle: "PRIX WOLF",
  weekDayID: 4
}, {
  allocation: 9114,
  category: "Steeplechase",
  direction: "Corde à droite",
  distance: 2190,
  equidiaPronostic: [9, 4, 11, 0, 13],
  field: "Pist en mâchefer",
  horses: ["Van Dusen", "Papi Chulo", "Happy Lyl", "Gran Stylo", "Tsitsipas", "Hussarde", "Andre Tor", "Courageously", "El Campana", "Munqad", "Ultimate Gift", "Romeo Santos", "Hallezsco", "Hani Bird", "Winning Point"],
  hour: "11:15",
  id: 25,
  location: "CAGNES/MER",
  locationCode: "R6",
  pace: "Gallop",
  raceCode: "C4",
  raceTitle: "PRIX INICIACION S",
  weekDayID: 4
}, {
  allocation: 67522,
  category: "Plat",
  direction: "Corde à gauche",
  distance: 2341,
  equidiaPronostic: [8, 5, 4, 13, 2],
  field: "Piste en herbe",
  horses: ["Gran Stylo", "Munqad", "Hallezsco", "Haka", "El Magnifico", "Papi Chulo", "Andre Tor", "Hani Bird", "Ultimate Gift", "Houston Sissi", "Courageously", "Tsitsipas", "El Campana", "Hussarde", "Romeo Santos", "Jarl"],
  hour: "11:45",
  id: 26,
  location: "VINCENNES",
  locationCode: "R5",
  pace: "Gallop",
  raceCode: "C5",
  raceTitle: "PRIX TROMPOLINO",
  weekDayID: 4
}, {
  allocation: 29236,
  category: "Saut de haies",
  direction: "Corde à droite",
  distance: 2653,
  equidiaPronostic: [8, 11, 2, 1, 3],
  field: "Pist en mâchefer",
  horses: ["Hallezsco", "Jarl", "Gran Stylo", "El Magnifico", "Andre Tor", "El Campana", "Hussarde", "Houston Sissi", "Van Dusen", "Heaven De Simm", "Papi Chulo", "Ultimate Gift", "Munqad"],
  hour: "12:15",
  id: 27,
  location: "DEAUVILLE",
  locationCode: "R1",
  pace: "Gallop",
  raceCode: "C6",
  raceTitle: "PRIX LA SOLIDARITE",
  weekDayID: 4
}, {
  allocation: 51379,
  category: "Crosscountry",
  direction: "Corde à gauche",
  distance: 2295,
  equidiaPronostic: [8, 10, 6, 5, 2],
  field: "Piste en pouzzolane",
  horses: ["Hussarde", "Heaven De Simm", "Tsitsipas", "Winning Point", "Happy Lyl", "Jarl", "El Magnifico", "Haka", "Ultimate Gift", "Hallezsco", "Courageously", "Andre Tor", "Hani Bird", "Romeo Santos"],
  hour: "08:15",
  id: 28,
  location: "AGEN LA GA.",
  locationCode: "R1",
  pace: "Gallop",
  raceCode: "C1",
  raceTitle: "PRIX VAL.MERVEILLES",
  weekDayID: 5
}, {
  allocation: 40480,
  category: "Crosscountry",
  direction: "Corde à gauche",
  distance: 2303,
  equidiaPronostic: [5, 7, 4, 8, 9],
  field: "Piste en sable",
  horses: ["Hani Bird", "Gran Stylo", "Courageously", "Heaven De Simm", "Tsitsipas", "Haka", "Happy Lyl", "El Magnifico", "Papi Chulo", "Houston Sissi", "Hallezsco", "Munqad", "Hussarde", "Ultimate Gift"],
  hour: "08:30",
  id: 29,
  location: "AGEN LA GA.",
  locationCode: "R5",
  pace: "Gallop",
  raceCode: "C2",
  raceTitle: "PRIX VALLEE VESUBIE",
  weekDayID: 5
}, {
  allocation: 59024,
  category: "Plat",
  direction: "Corde à gauche",
  distance: 2334,
  equidiaPronostic: [0, 6, 10, 7, 4],
  field: "Piste en pouzzolane",
  horses: ["El Campana", "Winning Point", "Van Dusen", "Munqad", "Haka", "Houston Sissi", "Happy Lyl", "Jarl", "Papi Chulo", "Tsitsipas", "Romeo Santos"],
  hour: "08:45",
  id: 30,
  location: "DEAUVILLE",
  locationCode: "R5",
  pace: "Gallop",
  raceCode: "C3",
  raceTitle: "PRIX ALLOWANCE 1700",
  weekDayID: 5
}, {
  allocation: 73429,
  category: "Attelé",
  direction: "Corde à droite",
  distance: 2176,
  equidiaPronostic: [2, 5, 8, 0, 4],
  field: "Piste en herbe",
  horses: ["Hussarde", "Haka", "Papi Chulo", "Gran Stylo", "Heaven De Simm", "Andre Tor", "El Campana", "Hani Bird", "Van Dusen", "Houston Sissi", "Happy Lyl", "El Magnifico"],
  hour: "09:45",
  id: 31,
  location: "AGEN LA GA.",
  locationCode: "R6",
  pace: "Trot",
  raceCode: "C4",
  raceTitle: "PRIX TROMPOLINO",
  weekDayID: 5
}, {
  allocation: 57922,
  category: "Saut de haies",
  direction: "Corde à droite",
  distance: 2007,
  equidiaPronostic: [6, 14, 12, 0, 3],
  field: "Pist en mâchefer",
  horses: ["El Magnifico", "El Campana", "Jarl", "Haka", "Van Dusen", "Tsitsipas", "Houston Sissi", "Winning Point", "Gran Stylo", "Hussarde", "Heaven De Simm", "Andre Tor", "Happy Lyl", "Courageously", "Ultimate Gift", "Hani Bird", "Hallezsco"],
  hour: "10:00",
  id: 32,
  location: "CAGNES/MER",
  locationCode: "R5",
  pace: "Gallop",
  raceCode: "C5",
  raceTitle: "PRIX VAL.MERVEILLES",
  weekDayID: 5
}, {
  allocation: 46752,
  category: " Monté",
  direction: "Corde à droite",
  distance: 2742,
  equidiaPronostic: [7, 4, 3, 6, 5],
  field: "Pist en mâchefer",
  horses: ["Jarl", "Munqad", "Romeo Santos", "Hallezsco", "Winning Point", "Hani Bird", "Ultimate Gift", "El Magnifico"],
  hour: "11:00",
  id: 33,
  location: "VINCENNES",
  locationCode: "R2",
  pace: "Trot",
  raceCode: "C6",
  raceTitle: "PRIX INICIACION S",
  weekDayID: 5
}, {
  allocation: 77128,
  category: " Monté",
  direction: "Corde à gauche",
  distance: 2963,
  equidiaPronostic: [8, 0, 2, 9, 1],
  field: "Pist en mâchefer",
  horses: ["Tsitsipas", "Hani Bird", "Winning Point", "Romeo Santos", "Munqad", "Van Dusen", "Ultimate Gift", "Happy Lyl", "Jarl", "El Campana"],
  hour: "09:00",
  id: 34,
  location: "VINCENNES",
  locationCode: "R3",
  pace: "Trot",
  raceCode: "C1",
  raceTitle: "PRIX VALLEE VESUBIE",
  weekDayID: 6
}, {
  allocation: 35260,
  category: "Attelé",
  direction: "Corde à gauche",
  distance: 2374,
  equidiaPronostic: [15, 14, 11, 9, 1],
  field: "Piste en pouzzolane",
  horses: ["Courageously", "Hani Bird", "Jarl", "Heaven De Simm", "Gran Stylo", "Hussarde", "Andre Tor", "Happy Lyl", "El Campana", "Haka", "Tsitsipas", "Ultimate Gift", "Hallezsco", "Van Dusen", "Munqad", "Papi Chulo", "Romeo Santos"],
  hour: "10:00",
  id: 35,
  location: "CAGNES/MER",
  locationCode: "R1",
  pace: "Trot",
  raceCode: "C2",
  raceTitle: "PRIX TROMPOLINO",
  weekDayID: 6
}, {
  allocation: 40064,
  category: "Crosscountry",
  direction: "Corde à gauche",
  distance: 2209,
  equidiaPronostic: [6, 0, 5, 1, 2],
  field: "Piste en sable fibré",
  horses: ["Hani Bird", "Winning Point", "Heaven De Simm", "Hussarde", "Andre Tor", "Gran Stylo", "Houston Sissi"],
  hour: "10:45",
  id: 36,
  location: "VINCENNES",
  locationCode: "R5",
  pace: "Gallop",
  raceCode: "C3",
  raceTitle: "PRIX DU MERCANTOUR",
  weekDayID: 6
}, {
  allocation: 78831,
  category: " Monté",
  direction: "Corde à droite",
  distance: 2716,
  equidiaPronostic: [8, 6, 5, 7, 0],
  field: "Pist en mâchefer",
  horses: ["Jarl", "Happy Lyl", "Papi Chulo", "Courageously", "Andre Tor", "Tsitsipas", "Gran Stylo", "Romeo Santos", "El Magnifico", "El Campana", "Hallezsco", "Van Dusen", "Hani Bird"],
  hour: "11:15",
  id: 37,
  location: "CAGNES/MER",
  locationCode: "R1",
  pace: "Trot",
  raceCode: "C4",
  raceTitle: "PRIX MAIDEN SPECIAL",
  weekDayID: 6
}]


exports.races =  races;